#!/bin/zsh

function heading {
  echo \\n# $1:\\n
}

case $(date +%a) in
  Sun )
    since='3.days'
    ;;
  Mon )
    since='4.days'
    ;;
  * )
    since='yesterday'
    ;;
esac

commits=$(git rev-list --all --since=$since)

dir=$(mktemp -d /tmp/git-yesterday.XXXXXX)

for sha in $commits; do
  git show $sha > $dir/$sha --color
done

less -r $dir/*

heading 'Commits'

git shortlog -w0,0,0 -s -n --since=$since --all |
  awk '{gsub(/^ +| +$/,"")}1' |
  awk -v OFS=" " '$1=$1' |
  awk '{ print "    "$0 }'

heading 'Lines'

git log --all --since=$since --pretty=tformat: --numstat |
  awk '{ added += $1; removed += $2; total += $1 - $2 } END { printf "%s Added\n%s Removed\n%s Total\n\n",added,removed,total }' |
  awk '{ print "    "$0 }'
